url: https://sol-robotics.github.io
baseurl:

# Site settings
title: Sol Robotics
email: contact-us@solrobotics.com
description: "Welding done right. Robotics Done Right."

intro:
  lead: "Welding done right."
  heading: "Robotics done right."

services:
  heading: "Heading for services."
  first:
    name: "E-Commerce"
    description: "Some description about E-Commerce."
  second:
    name: "Responsive Design"
    description: "Some description about Responsive Design."
  third:
    name: "Web Security"
    description: "Some description about Web Security."


# Team names, titles and social links
team:
  headings:
    top: "Some TOP text"
    bottom: "Some BOTTOM text."
people:
- name: Justin Hunt
  pic: 1
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Andrew Barkan
  pic: 2
  position: CPO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Zahi Kakish
  pic: 3
  position: COO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Varun Nalam
  pic: 4
  position: CTO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sol-robotics
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/sol-robotics

# Postal address (add as many lines as necessary)
address:
  - line: Palo Alto, CA 94301
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

contact:
  heading: "Feel free to contact us for more information!"

# Build settings
markdown: kramdown
permalink: pretty